[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
MPFI = "e50a78b8-6e2f-482e-b7c3-776aa2235d1a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
